language: java
jdk: oraclejdk8

addons:
  sonarcloud:
    organization: "spring-petclinic"
    token:
      secure: "Qkzrkt/dSSxj6psqp2a53lCWLUHX8iVxhDgskuJBiuwuF7wqLYe69eeb3efaiEoPZfMZ/BRflrg1EKRUb5ZWcxhri7UDzCr0WENhFnt63ry/sN1OCLz+PJxW63lMOTm+LYtEoRzSNOkSHN/T6o3CS7dAGkXFMKsDdThICgeAWEBd59AAEkTUS1DWJfccieFmr4YbHAsr30Tf/yIA6TKSdSojHJNC4/Ebs3hb6V+v3F/KXPWurq3NLb8i3ExIPReVJaTpB0nNmKrHwkZMTr+yweRBycLBOs4g3tuB8mc35zUceHi5GZYyavTHOHXBPXLbAI7gx6UcOi/3dIrtQCoAyRMVXbWkqqgAjUcMJRBZcWgA1cfgrHAgFYvKb8SbW+Dsx03ShJ7IlG9Iix9ySP7p43LN7Il8Mtv1RgvfWepw0GWbN2gBk7Mtv/laQTOvqCCPQe6n4wOX9ZjCmJq/0RjsWFXILNXHNXm7wd1/vW4+24nOzP9/0bLIU4iLHufGynZxv7WHBW6YuVee1nf19Urf4keOkgrqhQZdnWm3xMVwuONl5s7Niee1WMS53uEukr8wpppLtPyqodbgFTzhS4k8YqioZm9/68mvIUOg6abTPBEJbfcR7hi3EAKJL3SjONzJLAai8kKtCTmMgpsG5x3xVPRk0Hw7HsdCQ9O7Z8ET+kk="

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
