language: java
jdk: oraclejdk8

addons:
  sonarcloud:
    organization: "spring-petclinic"
    token:
      secure: $SONAR_TOKEN  # SONAR_TOKEN is defined in the Travis Repository Settings

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
